// Generated by Wrangler by running `wrangler types --env-interface Env`

interface Env {
	KV: KVNamespace;
	CHAIN: "sui";
	CF_ACCOUNT_ID: "fb5d95d6e0ff4055cbf5321f8dfc30e9";
	EMAIL_FROM: "Liber <login@davirain.xyz>";
	TURNKEY_ORG_ID: "f42d5685-5e5e-4139-98ad-4208cfb31295";
	TURNKEY_API_PUBLIC_KEY: "02f8fc5f38fad13ca949af3250a30b74604dd72f38506b429351f0062f96b6b1c5";
	GOOGLE_CLIENT_ID: "1021328086145-18jc2gqb4rdflor24ein4ub5pgkhi4qn.apps.googleusercontent.com";
	WALRUS_PUBLISHER: "https://publisher.walrus-testnet.walrus.space";
	WALRUS_AGGREGATOR: "https://aggregator.walrus-testnet.walrus.space";
	WALRUS_PUBLISH_TIMEOUT_MS: "800";
	ARWEAVE_GATEWAY: "https://arweave.net";
	SUI_RPC: "https://fullnode.testnet.sui.io:443";
	SUI_PACKAGE: "0xc292a0b4edbd6c523183342ab39c6f3526dd2d4d717ba0bfe5d899065fe9ce78";
	PAYMENT_CHAIN: "sui:testnet";
	AI_PROVIDER: "workers-ai";
	AI_MODEL: "@cf/qwen/qwen3-30b-a3b-fp8";
	AI_GATEWAY_CACHE_TTL: "604800";
	SEMANTIC_EMBEDDING_MODEL: "@cf/baai/bge-m3";
	PLATFORM_QUEUE_ENABLED: "true";
	R2: R2Bucket;
	DB: D1Database;
	MAILER: Fetcher;
	PLATFORM_QUEUE: Queue;
	VECTORIZE: VectorizeIndex;
	BROWSER: Fetcher;
	AI: Ai;
}
